version: '3.1'
services:
  elasticsearch:
    image: elasticsearch:7.17.4
    volumes:
      - ./C:\TheArenaAppDraft1\TheArenaApp1\TheArenaApp1\src\main\resources\elasticsearch.yml
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      
